import { transactionEnum, transactionType, chainEnum, transStatusEnum } from "../types/walletTypes";

export const transactionData: transactionType[] = [
  {
    mode: transactionEnum.in,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 12,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.switch,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 5,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.in,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 12,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.switch,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 5,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.in,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 12,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.switch,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 5,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.in,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 12,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.switch,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 5,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.done,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.saved,
  },
  {
    mode: transactionEnum.out,
    address: "0xSdao2USyAz9B6RBgZeFyNDePuQAxfzZZHE",
    time: new Date(2023, 11, 12, 16, 32),
    chain: chainEnum.solar,
    amount: 232,
    symbol: "SXP",
    usd: 20,
    status: transStatusEnum.saved,
  },
];
